/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.event.ListSelectionEvent;
import Manage.LoadImage;

/**
 *
 * @author Visual Studio
 */
public class ChooserBackground extends javax.swing.JDialog {

    private final DefaultListModel defaultListModel = new DefaultListModel();
    private JLabel lbBackgroundMain;

    /**
     * Creates new form ChooserBackground
     */
    public ChooserBackground(java.awt.Frame parent, boolean modal, JLabel lb) {
        super(parent, modal);
        initComponents();
        this.lbBackgroundMain = lb;
        this.setLocationRelativeTo(null);
        initComponents2();
    }

    private void initComponents2() {
        ArrayList<Image> imageList = new ArrayList<>();
        //Get image from source
        for (int i = 1; i <= 21; i++) {
            LoadImage loadImage = new LoadImage("mophongthuattoansapxep/lib/free-backgrounds/free-backgrounds-" + i + ".jpg");
            imageList.add(loadImage.getmImage());
            defaultListModel.addElement("free-backgrounds-" + i);
        }
        //Set model and add ListSelectionListener for JList
        jList1.setModel(defaultListModel);
        jList1.addListSelectionListener((ListSelectionEvent e) -> {
            if (!jList1.getValueIsAdjusting()) {
                LoadImage loadImage = new LoadImage("mophongthuattoansapxep/lib/free-backgrounds/" + jList1.getSelectedValue() + ".jpg");
                Image image = loadImage.getmImage().getScaledInstance(291, 142, Image.SCALE_SMOOTH);
                jLabel1.setIcon(new ImageIcon(image));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btnSaveBackground = new javax.swing.JButton();
        btnCancelBackground = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        btnSaveBackground.setText("Lưu hình nền");
        btnSaveBackground.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBackgroundActionPerformed(evt);
            }
        });

        btnCancelBackground.setText("Hủy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnSaveBackground)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSaveBackground)
                            .addComponent(btnCancelBackground))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveBackgroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBackgroundActionPerformed
        LoadImage loadImage = new LoadImage("mophongthuattoansapxep/lib/free-backgrounds/" + jList1.getSelectedValue() + ".jpg");
        Image image = loadImage.getmImage().getScaledInstance(1370, 660, Image.SCALE_SMOOTH);
        lbBackgroundMain.setIcon(new ImageIcon(image));
    }//GEN-LAST:event_btnSaveBackgroundActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelBackground;
    private javax.swing.JButton btnSaveBackground;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
